apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iwaskidding-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: ""
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - 'iwaskidding.com'
        - '*.iwaskidding.com'
      secretName: iwaskidding-tls-v2
  rules:
    - host: 'iwaskidding.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iwaskidding-service
                port:
                  number: 8080
    - host: '*.iwaskidding.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iwaskidding-service
                port:
                  number: 8080
